INSERT INTO ave (nombre) values ("Aguila");
INSERT INTO ave (nombre) values ("Aguila pescadora");
INSERT INTO ave (nombre) values ("Aguilucho");
INSERT INTO ave (nombre) values ("Aguilucho chico");
INSERT INTO ave (nombre) values ("Aguilucho de ala rojiza");
INSERT INTO ave (nombre) values ("Aguilucho de cola rojiza");
INSERT INTO ave (nombre) values ("Aguilucho de la Puna");
INSERT INTO ave (nombre) values ("Aguilucho langostero");
INSERT INTO ave (nombre) values ("Albatros de Buller");
INSERT INTO ave (nombre) values ("Albatros de cabeza gris");
INSERT INTO ave (nombre) values ("Albatros de ceja negra");
INSERT INTO ave (nombre) values ("Albatros de corona blanca");
INSERT INTO ave (nombre) values ("Albatros de frente blanca");
INSERT INTO ave (nombre) values ("Albatros de las Antipodas");
INSERT INTO ave (nombre) values ("Albatros de las Galápagos");
INSERT INTO ave (nombre) values ("Albatros de las Chatham");
INSERT INTO ave (nombre) values ("Albatros de pico delgado");
INSERT INTO ave (nombre) values ("Albatros errante");
INSERT INTO ave (nombre) values ("Albatros oscuro");
INSERT INTO ave (nombre) values ("Albatros oscuro de manto claro");
INSERT INTO ave (nombre) values ("Albatros real del Norte");
INSERT INTO ave (nombre) values ("Albatros real del Sur");
INSERT INTO ave (nombre) values ("Arañero cara negra");
INSERT INTO ave (nombre) values ("Ave del trópico de cola blanca");
INSERT INTO ave (nombre) values ("Ave del trópico de cola roja");
INSERT INTO ave (nombre) values ("Ave del trópico de pico rojo");
INSERT INTO ave (nombre) values ("Ave fragata");
INSERT INTO ave (nombre) values ("Ave fragata grande");
INSERT INTO ave (nombre) values ("Bailarín");
INSERT INTO ave (nombre) values ("Bailarín chico");
INSERT INTO ave (nombre) values ("Bailarín chico argentino");
INSERT INTO ave (nombre) values ("Bailarín chico peruano");
INSERT INTO ave (nombre) values ("Bandurria");
INSERT INTO ave (nombre) values ("Bandurria de la puna");
INSERT INTO ave (nombre) values ("Bandurrilla");
INSERT INTO ave (nombre) values ("Bandurrilla de Arica");
INSERT INTO ave (nombre) values ("Bandurrilla de la puna");
INSERT INTO ave (nombre) values ("Bandurrilla de las piedras");
INSERT INTO ave (nombre) values ("Bandurrilla de los bosques");
INSERT INTO ave (nombre) values ("Bandurrilla de pico recto");
INSERT INTO ave (nombre) values ("Batitú");
INSERT INTO ave (nombre) values ("Becacina");
INSERT INTO ave (nombre) values ("Becacina chica");
INSERT INTO ave (nombre) values ("Becacina de la puna");
INSERT INTO ave (nombre) values ("Becacina grande");
INSERT INTO ave (nombre) values ("Becacina pintada");
INSERT INTO ave (nombre) values ("Benteveo");
INSERT INTO ave (nombre) values ("Benteveo blanco y negro");
INSERT INTO ave (nombre) values ("Benteveo chico");
INSERT INTO ave (nombre) values ("Benteveo de vientre azufre");
INSERT INTO ave (nombre) values ("Benteveo real");
INSERT INTO ave (nombre) values ("Birro comun");
INSERT INTO ave (nombre) values ("Blanquillo");
INSERT INTO ave (nombre) values ("Burlisto castaño");
INSERT INTO ave (nombre) values ("Burrito negruzco");
INSERT INTO ave (nombre) values ("Cachaña");
INSERT INTO ave (nombre) values ("Cachudito");
INSERT INTO ave (nombre) values ("Cachudito de cresta blanca");
INSERT INTO ave (nombre) values ("Cachudito de Juan Fernandez");
INSERT INTO ave (nombre) values ("Cachudito del Norte");
INSERT INTO ave (nombre) values ("Caiquén");
INSERT INTO ave (nombre) values ("Caití");
INSERT INTO ave (nombre) values ("Canastero");
INSERT INTO ave (nombre) values ("Canastero chico");
INSERT INTO ave (nombre) values ("Canastero de cola larga");
INSERT INTO ave (nombre) values ("Canastero del Norte");
INSERT INTO ave (nombre) values ("Canastero del Sur");
INSERT INTO ave (nombre) values ("Canastero de las quebradas");
INSERT INTO ave (nombre) values ("Candelita americana");
INSERT INTO ave (nombre) values ("Canquén");
INSERT INTO ave (nombre) values ("Canquén colorado");
INSERT INTO ave (nombre) values ("Caranca");
INSERT INTO ave (nombre) values ("Carancho cordillerano");
INSERT INTO ave (nombre) values ("Carancho cordillerano del sur");
INSERT INTO ave (nombre) values ("Carancho negro");
INSERT INTO ave (nombre) values ("Carao");
INSERT INTO ave (nombre) values ("Cardenal");
INSERT INTO ave (nombre) values ("Carpinterito");
INSERT INTO ave (nombre) values ("Carpintero negro");
INSERT INTO ave (nombre) values ("Carpintero real");
INSERT INTO ave (nombre) values ("Cazamoscas chocolate");
INSERT INTO ave (nombre) values ("Cazamoscas de cola corta");
INSERT INTO ave (nombre) values ("Cazamoscas estriado");
INSERT INTO ave (nombre) values ("Cazamoscas picochato");
INSERT INTO ave (nombre) values ("Cazamoscas tijereta");
INSERT INTO ave (nombre) values ("Celestino");
INSERT INTO ave (nombre) values ("Cernícalo");
INSERT INTO ave (nombre) values ("Charlatán");
INSERT INTO ave (nombre) values ("Chercán");
INSERT INTO ave (nombre) values ("Chercán de las vegas");
INSERT INTO ave (nombre) values ("Chincol");
INSERT INTO ave (nombre) values ("Chiricoca");
INSERT INTO ave (nombre) values ("Chirihue");
INSERT INTO ave (nombre) values ("Chirihue austral");
INSERT INTO ave (nombre) values ("Chirihue azafrán");
INSERT INTO ave (nombre) values ("Chirihue cordillerano");
INSERT INTO ave (nombre) values ("Chirihue de la puna");
INSERT INTO ave (nombre) values ("Chirihue de Raimondi");
INSERT INTO ave (nombre) values ("Chirihue dorado");
INSERT INTO ave (nombre) values ("Chirihue verdoso");
INSERT INTO ave (nombre) values ("Chorlito cordillerano");
INSERT INTO ave (nombre) values ("Chorlo ártico");
INSERT INTO ave (nombre) values ("Chorlo cabezón");
INSERT INTO ave (nombre) values ("Chorlo chileno");
INSERT INTO ave (nombre) values ("Chorlo de campo");
INSERT INTO ave (nombre) values ("Chorlo de collar");
INSERT INTO ave (nombre) values ("Chorlo de doble collar");
INSERT INTO ave (nombre) values ("Chorlo de la Puna");
INSERT INTO ave (nombre) values ("Chorlo de Magallanes");
INSERT INTO ave (nombre) values ("Chorlo de pico grueso");
INSERT INTO ave (nombre) values ("Chorlo dorado");
INSERT INTO ave (nombre) values ("Chorlo dorado del Pacifico");
INSERT INTO ave (nombre) values ("Chorlo gritón");
INSERT INTO ave (nombre) values ("Chorlo nevado");
INSERT INTO ave (nombre) values ("Chorlo semipalmado");
INSERT INTO ave (nombre) values ("Choroy");
INSERT INTO ave (nombre) values ("Chucao");
INSERT INTO ave (nombre) values ("Chuncho");
INSERT INTO ave (nombre) values ("Chuncho del Norte");
INSERT INTO ave (nombre) values ("Churrete");
INSERT INTO ave (nombre) values ("Churrete acanelado");
INSERT INTO ave (nombre) values ("Churrete austral");
INSERT INTO ave (nombre) values ("Churrete chico");
INSERT INTO ave (nombre) values ("Churrete costero");
INSERT INTO ave (nombre) values ("Churrete costero peruano");
INSERT INTO ave (nombre) values ("Churrete de alas blancas");
INSERT INTO ave (nombre) values ("Churrete de alas crema");
INSERT INTO ave (nombre) values ("Churrín de la Mocha");
INSERT INTO ave (nombre) values ("Churrín del norte");
INSERT INTO ave (nombre) values ("Churrín del Sur");
INSERT INTO ave (nombre) values ("Cigüeña de cabeza pelada");
INSERT INTO ave (nombre) values ("Cisne coscoroba");
INSERT INTO ave (nombre) values ("Cisne de cuello negro");
INSERT INTO ave (nombre) values ("Codorniz");
INSERT INTO ave (nombre) values ("Colegial");
INSERT INTO ave (nombre) values ("Colegial del Norte");
INSERT INTO ave (nombre) values ("Colilarga");
INSERT INTO ave (nombre) values ("Comesebo chico");
INSERT INTO ave (nombre) values ("Comesebo de los tamarugales");
INSERT INTO ave (nombre) values ("Comesebo gigante");
INSERT INTO ave (nombre) values ("Comesebo grande");
INSERT INTO ave (nombre) values ("Comesebo negro");
INSERT INTO ave (nombre) values ("Cometocino de Arica");
INSERT INTO ave (nombre) values ("Cometocino de dorso castaño");
INSERT INTO ave (nombre) values ("Cometocino de Gay");
INSERT INTO ave (nombre) values ("Cometocino del norte");
INSERT INTO ave (nombre) values ("Cometocino patagónico");
INSERT INTO ave (nombre) values ("Concón");
INSERT INTO ave (nombre) values ("Cóndor de Los Andes");
INSERT INTO ave (nombre) values ("Corbatita");
INSERT INTO ave (nombre) values ("Corbatita de doble collar");
INSERT INTO ave (nombre) values ("Corbatita overo");
INSERT INTO ave (nombre) values ("Cormorán antártico");
INSERT INTO ave (nombre) values ("Cormorán de las rocas");
INSERT INTO ave (nombre) values ("Cormorán Imperial");
INSERT INTO ave (nombre) values ("Cortarramas");
INSERT INTO ave (nombre) values ("Cotorra argentina");
INSERT INTO ave (nombre) values ("Cuclillo de pico amarillo");
INSERT INTO ave (nombre) values ("Cuclillo de pico negro");
INSERT INTO ave (nombre) values ("Cuervo de pantano");
INSERT INTO ave (nombre) values ("Cuervo de pantano de cara pelada");
INSERT INTO ave (nombre) values ("Cuervo de pantano de la Puna");
INSERT INTO ave (nombre) values ("Diuca");
INSERT INTO ave (nombre) values ("Diuca de alas blancas");
INSERT INTO ave (nombre) values ("Diucón");
INSERT INTO ave (nombre) values ("Dormilona cenicienta");
INSERT INTO ave (nombre) values ("Dormilona chica");
INSERT INTO ave (nombre) values ("Dormilona de ceja blanca");
INSERT INTO ave (nombre) values ("Dormilona de frente negra");
INSERT INTO ave (nombre) values ("Dormilona de la Puna");
INSERT INTO ave (nombre) values ("Dormilona de nuca rojiza");
INSERT INTO ave (nombre) values ("Dormilona fraile");
INSERT INTO ave (nombre) values ("Dormilona gigante");
INSERT INTO ave (nombre) values ("Dormilona rufa");
INSERT INTO ave (nombre) values ("Dormilona tontito");
INSERT INTO ave (nombre) values ("Espátula");
INSERT INTO ave (nombre) values ("Estornino pinto");
INSERT INTO ave (nombre) values ("Faisán");
INSERT INTO ave (nombre) values ("Fardela atlántica");
INSERT INTO ave (nombre) values ("Fardela blanca");
INSERT INTO ave (nombre) values ("Fardela blanca de Juan Fernandez");
INSERT INTO ave (nombre) values ("Fardela blanca de Masatierra");
INSERT INTO ave (nombre) values ("Fardela capirotada");
INSERT INTO ave (nombre) values ("Fardela chica");
INSERT INTO ave (nombre) values ("Fardela de cabeza parda");
INSERT INTO ave (nombre) values ("Fardela de Cook");
INSERT INTO ave (nombre) values ("Fardela de dorso gris");
INSERT INTO ave (nombre) values ("Fardela de Fénix");
INSERT INTO ave (nombre) values ("Fardela de frente blanca");
INSERT INTO ave (nombre) values ("Fardela de Henderson");
INSERT INTO ave (nombre) values ("Fardela de Kerguelen");
INSERT INTO ave (nombre) values ("Fardela de Masafuera");
INSERT INTO ave (nombre) values ("Fardela de Murphy");
INSERT INTO ave (nombre) values ("Fardela de Nueva Zelanda");
INSERT INTO ave (nombre) values ("Fardela de Parkinson");
INSERT INTO ave (nombre) values ("Fardela de Pascua");
INSERT INTO ave (nombre) values ("Fardela del Pacifico");
INSERT INTO ave (nombre) values ("Fardela gris");
INSERT INTO ave (nombre) values ("Fardela heráldica");
INSERT INTO ave (nombre) values ("Fardela negra");
INSERT INTO ave (nombre) values ("Fardela negra de Juan Fernandez");
INSERT INTO ave (nombre) values ("Fardela negra de patas pálidas");
INSERT INTO ave (nombre) values ("Fardela negra grande");
INSERT INTO ave (nombre) values ("Fardela Taiko");
INSERT INTO ave (nombre) values ("Fardela tropical");
INSERT INTO ave (nombre) values ("Federal");
INSERT INTO ave (nombre) values ("Fio-fio");
INSERT INTO ave (nombre) values ("Fio-fio grande");
INSERT INTO ave (nombre) values ("Flamenco chileno");
INSERT INTO ave (nombre) values ("Gallina ciega");
INSERT INTO ave (nombre) values ("Gallina ciega chica");
INSERT INTO ave (nombre) values ("Gallina ciega boreal");
INSERT INTO ave (nombre) values ("Gallina ciega peruana");
INSERT INTO ave (nombre) values ("Garcita azulada");
INSERT INTO ave (nombre) values ("Garza azul");
INSERT INTO ave (nombre) values ("Garza boyera o Garza bueyera");
INSERT INTO ave (nombre) values ("Garza chica");
INSERT INTO ave (nombre) values ("Garza chiflon");
INSERT INTO ave (nombre) values ("Garza cuca");
INSERT INTO ave (nombre) values ("Garza grande");
INSERT INTO ave (nombre) values ("Garza tricolor");
INSERT INTO ave (nombre) values ("Gavilan pajarero");
INSERT INTO ave (nombre) values ("Gaviota andina");
INSERT INTO ave (nombre) values ("Gaviota argentea");
INSERT INTO ave (nombre) values ("Gaviota austral");
INSERT INTO ave (nombre) values ("Gaviota cáhuil");
INSERT INTO ave (nombre) values ("Gaviota de Bonaparte");
INSERT INTO ave (nombre) values ("Gaviota de capucho gris");
INSERT INTO ave (nombre) values ("Gaviota de Franklin");
INSERT INTO ave (nombre) values ("Gaviota de las Galápagos");
INSERT INTO ave (nombre) values ("Gaviota de Sabine");
INSERT INTO ave (nombre) values ("Gaviota dominicana");
INSERT INTO ave (nombre) values ("Gaviota garuma");
INSERT INTO ave (nombre) values ("Gaviota peruana");
INSERT INTO ave (nombre) values ("Gaviota reidora");
INSERT INTO ave (nombre) values ("Gaviotín albo");
INSERT INTO ave (nombre) values ("Gaviotín antártico");
INSERT INTO ave (nombre) values ("Gaviotín apizarrado");
INSERT INTO ave (nombre) values ("Gaviotín ártico");
INSERT INTO ave (nombre) values ("Gaviotín boreal");
INSERT INTO ave (nombre) values ("Gaviotín chico");
INSERT INTO ave (nombre) values ("Gaviotín chico boreal");
INSERT INTO ave (nombre) values ("Gaviotín de bridas");
INSERT INTO ave (nombre) values ("Gaviotín de pico grande");
INSERT INTO ave (nombre) values ("Gaviotín de San Ambrosio");
INSERT INTO ave (nombre) values ("Gaviotín de San Félix");
INSERT INTO ave (nombre) values ("Gaviotín de Sandwich");
INSERT INTO ave (nombre) values ("Gaviotín elegante");
INSERT INTO ave (nombre) values ("Gaviotín monja");
INSERT INTO ave (nombre) values ("Gaviotín negro");
INSERT INTO ave (nombre) values ("Gaviotín oscuro");
INSERT INTO ave (nombre) values ("Gaviotín pascuense");
INSERT INTO ave (nombre) values ("Gaviotín pico grueso");
INSERT INTO ave (nombre) values ("Gaviotín piquerito");
INSERT INTO ave (nombre) values ("Gaviotín real");
INSERT INTO ave (nombre) values ("Gaviotín sudamericano");
INSERT INTO ave (nombre) values ("Golondrina barranquera");
INSERT INTO ave (nombre) values ("Golondrina bermeja");
INSERT INTO ave (nombre) values ("Golondrina chilena");
INSERT INTO ave (nombre) values ("Golondrina de cabeza rojiza");
INSERT INTO ave (nombre) values ("Golondrina de dorso negro");
INSERT INTO ave (nombre) values ("Golondrina de los riscos");
INSERT INTO ave (nombre) values ("Golondrina domestica");
INSERT INTO ave (nombre) values ("Golondrina grande");
INSERT INTO ave (nombre) values ("Golondrina negra");
INSERT INTO ave (nombre) values ("Golondrina negra peruana");
INSERT INTO ave (nombre) values ("Golondrina parda");
INSERT INTO ave (nombre) values ("Golondrina de mar");
INSERT INTO ave (nombre) values ("Golondrina de mar andina");
INSERT INTO ave (nombre) values ("Golondrina de mar boreal");
INSERT INTO ave (nombre) values ("Golondrina de mar chica");
INSERT INTO ave (nombre) values ("Golondrina de mar de ceja blanca");
INSERT INTO ave (nombre) values ("Golondrina de mar de collar");
INSERT INTO ave (nombre) values ("Golondrina de mar de garganta blanca");
INSERT INTO ave (nombre) values ("Golondrina de mar de vientre blanco");
INSERT INTO ave (nombre) values ("Golondrina de mar de vientre negro");
INSERT INTO ave (nombre) values ("Golondrina de mar negra");
INSERT INTO ave (nombre) values ("Golondrina de mar oscura");
INSERT INTO ave (nombre) values ("Golondrina de mar peruana");
INSERT INTO ave (nombre) values ("Golondrina de mar pincoya");
INSERT INTO ave (nombre) values ("Golondrina de mar subantártica");
INSERT INTO ave (nombre) values ("Gorrión");
INSERT INTO ave (nombre) values ("Guacharo");
INSERT INTO ave (nombre) values ("Guanay");
INSERT INTO ave (nombre) values ("Halcón de pecho naranja");
INSERT INTO ave (nombre) values ("Halcón perdiguero");
INSERT INTO ave (nombre) values ("Halcón peregrino");
INSERT INTO ave (nombre) values ("Halcón reidor");
INSERT INTO ave (nombre) values ("Huairavillo");
INSERT INTO ave (nombre) values ("Huairavillo de dorso negro");
INSERT INTO ave (nombre) values ("Huairavo");
INSERT INTO ave (nombre) values ("Huairavo de corona amarilla");
INSERT INTO ave (nombre) values ("Huala");
INSERT INTO ave (nombre) values ("Hued-hued castaño");
INSERT INTO ave (nombre) values ("Hued-hued del sur");
INSERT INTO ave (nombre) values ("Jacana");
INSERT INTO ave (nombre) values ("Jílguero");
INSERT INTO ave (nombre) values ("Jílguero cordillerano");
INSERT INTO ave (nombre) values ("Jílguero grande");
INSERT INTO ave (nombre) values ("Jílguero negro");
INSERT INTO ave (nombre) values ("Jílguero peruano");
INSERT INTO ave (nombre) values ("Jote de cabeza colorada");
INSERT INTO ave (nombre) values ("Jote de cabeza negra");
INSERT INTO ave (nombre) values ("Lavandera blanca");
INSERT INTO ave (nombre) values ("Lechuza");
INSERT INTO ave (nombre) values ("Lile");
INSERT INTO ave (nombre) values ("Loica");
INSERT INTO ave (nombre) values ("Loica argentina");
INSERT INTO ave (nombre) values ("Loica peruana");
INSERT INTO ave (nombre) values ("Loro de cara roja");
INSERT INTO ave (nombre) values ("Loro mitrata");
INSERT INTO ave (nombre) values ("Martín pescador");
INSERT INTO ave (nombre) values ("Martín pescador chico");
INSERT INTO ave (nombre) values ("Matacaballos");
INSERT INTO ave (nombre) values ("Matacaballos de pico liso");
INSERT INTO ave (nombre) values ("Mero");
INSERT INTO ave (nombre) values ("Mero chico");
INSERT INTO ave (nombre) values ("Mero de ala canela");
INSERT INTO ave (nombre) values ("Mero de la puna");
INSERT INTO ave (nombre) values ("Mero de Tarapacá");
INSERT INTO ave (nombre) values ("Mero gaucho");
INSERT INTO ave (nombre) values ("Milano tijereta");
INSERT INTO ave (nombre) values ("Minero");
INSERT INTO ave (nombre) values ("Minero austral");
INSERT INTO ave (nombre) values ("Minero chico");
INSERT INTO ave (nombre) values ("Minero cordillerano");
INSERT INTO ave (nombre) values ("Minero de la Puna");
INSERT INTO ave (nombre) values ("Minero de pico delgado");
INSERT INTO ave (nombre) values ("Minero grande");
INSERT INTO ave (nombre) values ("Mirlo");
INSERT INTO ave (nombre) values ("Mirlo de pico corto");
INSERT INTO ave (nombre) values ("Monjita americana");
INSERT INTO ave (nombre) values ("Monjita blanca");
INSERT INTO ave (nombre) values ("Monjita castaña");
INSERT INTO ave (nombre) values ("Monjita coronada");
INSERT INTO ave (nombre) values ("Mosqueta boreal");
INSERT INTO ave (nombre) values ("Naranjero");
INSERT INTO ave (nombre) values ("Negrillo");
INSERT INTO ave (nombre) values ("Nuco");
INSERT INTO ave (nombre) values ("Ñacundá");
INSERT INTO ave (nombre) values ("Ñandú");
INSERT INTO ave (nombre) values ("Pájaro amarillo");
INSERT INTO ave (nombre) values ("Pájaro plomo");
INSERT INTO ave (nombre) values ("Paloma antártica");
INSERT INTO ave (nombre) values ("Paloma de alas blancas");
INSERT INTO ave (nombre) values ("Paloma de alas moteadas");
INSERT INTO ave (nombre) values ("Paloma doméstica");
INSERT INTO ave (nombre) values ("Paloma picazuro");
INSERT INTO ave (nombre) values ("Parina chica");
INSERT INTO ave (nombre) values ("Parina grande");
INSERT INTO ave (nombre) values ("Patagón");
INSERT INTO ave (nombre) values ("Pato anteojillo");
INSERT INTO ave (nombre) values ("Pato capuchino");
INSERT INTO ave (nombre) values ("Pato castaño");
INSERT INTO ave (nombre) values ("Pato colorado");
INSERT INTO ave (nombre) values ("Pato cortacorrientes");
INSERT INTO ave (nombre) values ("Pato crestudo");
INSERT INTO ave (nombre) values ("Pato criollo");
INSERT INTO ave (nombre) values ("Pato cuchara");
INSERT INTO ave (nombre) values ("Pato de alas azules");
INSERT INTO ave (nombre) values ("Pato de collar");
INSERT INTO ave (nombre) values ("Pato gargantillo");
INSERT INTO ave (nombre) values ("Pato jergón chico");
INSERT INTO ave (nombre) values ("Pato jergón grande");
INSERT INTO ave (nombre) values ("Pato juarjual");
INSERT INTO ave (nombre) values ("Pato negro");
INSERT INTO ave (nombre) values ("Pato puna");
INSERT INTO ave (nombre) values ("Pato rana de pico ancho");
INSERT INTO ave (nombre) values ("Pato rana de pico delgado");
INSERT INTO ave (nombre) values ("Pato real");
INSERT INTO ave (nombre) values ("Pato rinconero");
INSERT INTO ave (nombre) values ("Pato silbón");
INSERT INTO ave (nombre) values ("Pato silbón de ala blanca");
INSERT INTO ave (nombre) values ("Pato silbón pampa");
INSERT INTO ave (nombre) values ("Pelícano");
INSERT INTO ave (nombre) values ("Pelícano pardo");
INSERT INTO ave (nombre) values ("Pepitero");
INSERT INTO ave (nombre) values ("Pequén");
INSERT INTO ave (nombre) values ("Perdicita");
INSERT INTO ave (nombre) values ("Perdicita cojón");
INSERT INTO ave (nombre) values ("Perdicita cordillerana");
INSERT INTO ave (nombre) values ("Perdicita cordillerana austral");
INSERT INTO ave (nombre) values ("Perdiz austral");
INSERT INTO ave (nombre) values ("Perdiz chilena");
INSERT INTO ave (nombre) values ("Perdiz copetona");
INSERT INTO ave (nombre) values ("Perdiz cordillerana");
INSERT INTO ave (nombre) values ("Perdiz cordillerana de Arica");
INSERT INTO ave (nombre) values ("Perdiz de la Puna");
INSERT INTO ave (nombre) values ("Perico cordillerano");
INSERT INTO ave (nombre) values ("Perrito");
INSERT INTO ave (nombre) values ("Petrel antártico");
INSERT INTO ave (nombre) values ("Petrel azulado");
INSERT INTO ave (nombre) values ("Petrel boreal");
INSERT INTO ave (nombre) values ("Petrel damero");
INSERT INTO ave (nombre) values ("Petrel de alas negras");
INSERT INTO ave (nombre) values ("Petrel de cara gris");
INSERT INTO ave (nombre) values ("Petrel de collar gris");
INSERT INTO ave (nombre) values ("Petrel de Gould");
INSERT INTO ave (nombre) values ("Petrel de las Galapagos");
INSERT INTO ave (nombre) values ("Petrel de las nieves");
INSERT INTO ave (nombre) values ("Petrel gigante antártico");
INSERT INTO ave (nombre) values ("Petrel gigante subantártico");
INSERT INTO ave (nombre) values ("Petrel moteado");
INSERT INTO ave (nombre) values ("Petrel plateado");
INSERT INTO ave (nombre) values ("Petrel-paloma antártico");
INSERT INTO ave (nombre) values ("Petrel-paloma chico");
INSERT INTO ave (nombre) values ("Petrel-paloma de pico ancho");
INSERT INTO ave (nombre) values ("Petrel-paloma de pico delgado");
INSERT INTO ave (nombre) values ("Peuco");
INSERT INTO ave (nombre) values ("Peuquito");
INSERT INTO ave (nombre) values ("Pibi ahumado");
INSERT INTO ave (nombre) values ("Pibi occidental");
INSERT INTO ave (nombre) values ("Picabuey");
INSERT INTO ave (nombre) values ("Picaflor");
INSERT INTO ave (nombre) values ("Picaflor azul");
INSERT INTO ave (nombre) values ("Picaflor cometa");
INSERT INTO ave (nombre) values ("Picaflor comun argentino");
INSERT INTO ave (nombre) values ("Picaflor cordillerano");
INSERT INTO ave (nombre) values ("Picaflor de Arica");
INSERT INTO ave (nombre) values ("Picaflor de Cora");
INSERT INTO ave (nombre) values ("Picaflor de Juan Fernández");
INSERT INTO ave (nombre) values ("Picaflor de la Puna");
INSERT INTO ave (nombre) values ("Picaflor del Norte");
INSERT INTO ave (nombre) values ("Picaflor gigante");
INSERT INTO ave (nombre) values ("Picurio");
INSERT INTO ave (nombre) values ("Pidén");
INSERT INTO ave (nombre) values ("Pidén austral");
INSERT INTO ave (nombre) values ("Pidén moteado");
INSERT INTO ave (nombre) values ("Pidencito");
INSERT INTO ave (nombre) values ("Pillo");
INSERT INTO ave (nombre) values ("Pilpilén");
INSERT INTO ave (nombre) values ("Pilpilén austral");
INSERT INTO ave (nombre) values ("Pilpilén negro");
INSERT INTO ave (nombre) values ("Pimpollo");
INSERT INTO ave (nombre) values ("Pimpollo tobiano");
INSERT INTO ave (nombre) values ("Pingüino de Adelia");
INSERT INTO ave (nombre) values ("Pingüino de barbijo");
INSERT INTO ave (nombre) values ("Pingüino de Humboldt");
INSERT INTO ave (nombre) values ("Pingüino de Magallanes");
INSERT INTO ave (nombre) values ("Pingüino de penacho amarillo");
INSERT INTO ave (nombre) values ("Pingüino de las Snares");
INSERT INTO ave (nombre) values ("Pingüino emperador");
INSERT INTO ave (nombre) values ("Pingüino enano");
INSERT INTO ave (nombre) values ("Pingüino macaroni");
INSERT INTO ave (nombre) values ("Pingüino papúa");
INSERT INTO ave (nombre) values ("Pingüino real");
INSERT INTO ave (nombre) values ("Pingüino rey");
INSERT INTO ave (nombre) values ("Piquero");
INSERT INTO ave (nombre) values ("Piquero blanco");
INSERT INTO ave (nombre) values ("Piquero de Brewster (Piquero de Cocos)");
INSERT INTO ave (nombre) values ("Piquero de Nazca");
INSERT INTO ave (nombre) values ("Piquero de patas azules");
INSERT INTO ave (nombre) values ("Piquero de patas coloradas");
INSERT INTO ave (nombre) values ("Piranga");
INSERT INTO ave (nombre) values ("Pirincho");
INSERT INTO ave (nombre) values ("Pitajo gris");
INSERT INTO ave (nombre) values ("Pitajo rojizo");
INSERT INTO ave (nombre) values ("Pitanguá");
INSERT INTO ave (nombre) values ("Pitiayumí");
INSERT INTO ave (nombre) values ("Pitio");
INSERT INTO ave (nombre) values ("Pitio del Norte");
INSERT INTO ave (nombre) values ("Pitotoy chico");
INSERT INTO ave (nombre) values ("Pitotoy grande");
INSERT INTO ave (nombre) values ("Pitotoy solitario");
INSERT INTO ave (nombre) values ("Piuquén");
INSERT INTO ave (nombre) values ("Pizarrita");
INSERT INTO ave (nombre) values ("Platero");
INSERT INTO ave (nombre) values ("Playero acuminado");
INSERT INTO ave (nombre) values ("Playero ártico");
INSERT INTO ave (nombre) values ("Playero blanco");
INSERT INTO ave (nombre) values ("Playero canela");
INSERT INTO ave (nombre) values ("Playero de Baird");
INSERT INTO ave (nombre) values ("Playero de las rompientes");
INSERT INTO ave (nombre) values ("Playero de lomo blanco");
INSERT INTO ave (nombre) values ("Playero de patas largas");
INSERT INTO ave (nombre) values ("Playero enano");
INSERT INTO ave (nombre) values ("Playero grande");
INSERT INTO ave (nombre) values ("Playero gris");
INSERT INTO ave (nombre) values ("Playero manchado");
INSERT INTO ave (nombre) values ("Playero occidental");
INSERT INTO ave (nombre) values ("Playero pectoral");
INSERT INTO ave (nombre) values ("Playero semipalmado");
INSERT INTO ave (nombre) values ("Playero ventinegro");
INSERT INTO ave (nombre) values ("Playero vuelvepiedras");
INSERT INTO ave (nombre) values ("Playero zarapito");
INSERT INTO ave (nombre) values ("Plebeyo");
INSERT INTO ave (nombre) values ("Pollito de mar boreal");
INSERT INTO ave (nombre) values ("Pollito de mar rojizo");
INSERT INTO ave (nombre) values ("Pollito de mar tricolor");
INSERT INTO ave (nombre) values ("Queltehue");
INSERT INTO ave (nombre) values ("Queltehue de la Puna");
INSERT INTO ave (nombre) values ("Quetru chileno");
INSERT INTO ave (nombre) values ("Quetru no volador");
INSERT INTO ave (nombre) values ("Quetru volador");
INSERT INTO ave (nombre) values ("Rara");
INSERT INTO ave (nombre) values ("Rayadito");
INSERT INTO ave (nombre) values ("Rayadito de Masafuera");
INSERT INTO ave (nombre) values ("Rayadito subantartico");
INSERT INTO ave (nombre) values ("Rayador");
INSERT INTO ave (nombre) values ("Reinita acuatica");
INSERT INTO ave (nombre) values ("Reinita de Canada");
INSERT INTO ave (nombre) values ("Reinita de dorso verde");
INSERT INTO ave (nombre) values ("Reinita de garganta naranja");
INSERT INTO ave (nombre) values ("Reinita de Tennessee");
INSERT INTO ave (nombre) values ("Rey del bosque");
INSERT INTO ave (nombre) values ("Run-run");
INSERT INTO ave (nombre) values ("Saca-tu-real");
INSERT INTO ave (nombre) values ("Salteador chico");
INSERT INTO ave (nombre) values ("Salteador chileno");
INSERT INTO ave (nombre) values ("Salteador de cola larga");
INSERT INTO ave (nombre) values ("Salteador pardo");
INSERT INTO ave (nombre) values ("Salteador polar");
INSERT INTO ave (nombre) values ("Salteador pomarino");
INSERT INTO ave (nombre) values ("Semillero");
INSERT INTO ave (nombre) values ("Semillero peruano");
INSERT INTO ave (nombre) values ("Siete-colores");
INSERT INTO ave (nombre) values ("Tagua");
INSERT INTO ave (nombre) values ("Tagua andina");
INSERT INTO ave (nombre) values ("Tagua chica");
INSERT INTO ave (nombre) values ("Tagua cornuda");
INSERT INTO ave (nombre) values ("Tagua de frente roja");
INSERT INTO ave (nombre) values ("Tagua gigante");
INSERT INTO ave (nombre) values ("Tagüita");
INSERT INTO ave (nombre) values ("Tagüita del Norte");
INSERT INTO ave (nombre) values ("Tagüita purpúrea");
INSERT INTO ave (nombre) values ("Tapaculo");
INSERT INTO ave (nombre) values ("Tenca");
INSERT INTO ave (nombre) values ("Tenca calandria");
INSERT INTO ave (nombre) values ("Tenca de alas blancas");
INSERT INTO ave (nombre) values ("Tenca de cola larga");
INSERT INTO ave (nombre) values ("Tenca de dorso castaño");
INSERT INTO ave (nombre) values ("Tenca patagónica");
INSERT INTO ave (nombre) values ("Tersina");
INSERT INTO ave (nombre) values ("Tijeral");
INSERT INTO ave (nombre) values ("Tijeral listado");
INSERT INTO ave (nombre) values ("Tiuque");
INSERT INTO ave (nombre) values ("Torcaza");
INSERT INTO ave (nombre) values ("Tordo");
INSERT INTO ave (nombre) values ("Tordo bayo");
INSERT INTO ave (nombre) values ("Tórtola");
INSERT INTO ave (nombre) values ("Tórtola cordillerana");
INSERT INTO ave (nombre) values ("Tortolita boliviana");
INSERT INTO ave (nombre) values ("Tortolita de la Puna");
INSERT INTO ave (nombre) values ("Tortolita cuyana");
INSERT INTO ave (nombre) values ("Tortolita quiguagua");
INSERT INTO ave (nombre) values ("Tortolita rojiza");
INSERT INTO ave (nombre) values ("Trabajador");
INSERT INTO ave (nombre) values ("Traro");
INSERT INTO ave (nombre) values ("Tricahue");
INSERT INTO ave (nombre) values ("Trile");
INSERT INTO ave (nombre) values ("Trile de cabeza canela");
INSERT INTO ave (nombre) values ("Tucúquere");
INSERT INTO ave (nombre) values ("Tuquito gris");
INSERT INTO ave (nombre) values ("Turca");
INSERT INTO ave (nombre) values ("Turpial norteño");
INSERT INTO ave (nombre) values ("Turpial variable");
INSERT INTO ave (nombre) values ("Urutau");
INSERT INTO ave (nombre) values ("Vari");
INSERT INTO ave (nombre) values ("Vari huevetero");
INSERT INTO ave (nombre) values ("Vencejo chico");
INSERT INTO ave (nombre) values ("Vencejo de chimenea");
INSERT INTO ave (nombre) values ("Vencejo de collar blanco");
INSERT INTO ave (nombre) values ("Verderón de ojos rojos");
INSERT INTO ave (nombre) values ("Viudita");
INSERT INTO ave (nombre) values ("Viudita negra");
INSERT INTO ave (nombre) values ("Yal");
INSERT INTO ave (nombre) values ("Yal austral");
INSERT INTO ave (nombre) values ("Yal cordillerano");
INSERT INTO ave (nombre) values ("Yeco");
INSERT INTO ave (nombre) values ("Yunco");
INSERT INTO ave (nombre) values ("Yunco de Magallanes");
INSERT INTO ave (nombre) values ("Yunco de los canales");
INSERT INTO ave (nombre) values ("Zanate mexicano");
INSERT INTO ave (nombre) values ("Zarapito");
INSERT INTO ave (nombre) values ("Zarapito boreal");
INSERT INTO ave (nombre) values ("Zarapito de cola barrada");
INSERT INTO ave (nombre) values ("Zarapito de pico recto");
INSERT INTO ave (nombre) values ("Zarapito moteado");
INSERT INTO ave (nombre) values ("Zarapito polinésico");
INSERT INTO ave (nombre) values ("Zorzal");
INSERT INTO ave (nombre) values ("Zorzal argentino");
INSERT INTO ave (nombre) values ("Zorzal manchado");
INSERT INTO ave (nombre) values ("Zorzal negro");
INSERT INTO ave (nombre) values ("Zorzal tropical");
INSERT INTO ave (nombre) values ("Zorzalito de Swainson");
