-- MySQL Script generated by MySQL Workbench
-- Mon Sep  7 22:38:49 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tarea2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tarea2` ;

-- -----------------------------------------------------
-- Schema tarea2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tarea2` DEFAULT CHARACTER SET utf8 ;
USE `tarea2` ;

-- -----------------------------------------------------
-- Table `tarea2`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tarea2`.`region` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tarea2`.`comuna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tarea2`.`comuna` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NOT NULL,
  `region_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comuna_region1_idx` (`region_id` ASC),
  CONSTRAINT `fk_comuna_region1`
    FOREIGN KEY (`region_id`)
    REFERENCES `tarea2`.`region` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tarea2`.`voluntario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tarea2`.`voluntario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `fecha_registro` DATETIME NOT NULL,
  `comuna_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_voluntario_comuna1_idx` (`comuna_id` ASC),
  CONSTRAINT `fk_voluntario_comuna1`
    FOREIGN KEY (`comuna_id`)
    REFERENCES `tarea2`.`comuna` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tarea2`.`ave`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tarea2`.`ave` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tarea2`.`avistamiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tarea2`.`avistamiento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `voluntario_id` INT NOT NULL,
  `ave_id` INT NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  `lugar` VARCHAR(200) NOT NULL,
  `descripcion` TEXT(500) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_avitamiento_voluntario1_idx` (`voluntario_id` ASC),
  INDEX `fk_avistamiento_ave1_idx` (`ave_id` ASC),
  CONSTRAINT `fk_avistamiento_voluntario1`
    FOREIGN KEY (`voluntario_id`)
    REFERENCES `tarea2`.`voluntario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avistamiento_ave1`
    FOREIGN KEY (`ave_id`)
    REFERENCES `tarea2`.`ave` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tarea2`.`registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tarea2`.`registro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ruta_archivo` VARCHAR(300) NOT NULL,
  `nombre_archivo` VARCHAR(300) NOT NULL,
  `avistamiento_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_registro_avistamiento1_idx` (`avistamiento_id` ASC),
  CONSTRAINT `fk_registro_avistamiento1`
    FOREIGN KEY (`avistamiento_id`)
    REFERENCES `tarea2`.`avistamiento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

CREATE USER 'cc5002'@'%' IDENTIFIED BY 'programacionweb';
GRANT ALL PRIVILEGES ON tarea2.* TO 'cc5002'@'%';
FLUSH PRIVILEGES;
